# Generated by Django 2.0.1 on 2018-03-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('ip', models.GenericIPAddressField(protocol='ipv4')),
                ('port', models.IntegerField()),
                ('user', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=18)),
                ('pwd', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=12)),
                ('tel', models.CharField(max_length=11)),
                ('key', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='host_user',
            field=models.ManyToManyField(to='host_manage.UserInfo'),
        ),
    ]
