# Generated by Django 2.0.1 on 2018-02-01 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host_manage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='trl',
            new_name='tel',
        ),
    ]
